### ISSUE TITLE
Github backend doesn't work with non-OAuth type apps

### ISSUE THREAD

**Issue by ghost** [python-social-auth/social-core#111]
Now unless I'm misunderstanding something, this library does not work with github. But not the regular OAuth type apps, regular Github apps. Despite the endpoints and everything being the same, this type of app (which I guess is differentiated by the token) does not support the `redirect_state` parameter. It kept complaining about the `redirect_uri` not matching up exactly, despite the exact same set up working with regular OAuth apps.

I solved this by subclassing the backend and overriding the option.

    class MyGithubOAuth2(GithubOAuth2):
        REDIRECT_STATE = False

Am I doing something wrong, or was this never tested? Perhaps just not supported? Don't see anything in the documentation regarding this.

**Comment by nkprince007** [comment]
I have the same problem too. Although it does not work like OAuth, we need to have some sort of storage mechanism with Django. 
Using PyJWT with the provided RSA key, there should be some method of generating an access token.

**Comment by sils** [comment]
Judging from commit logs @omab might be able to help us here?

Can we help making this happen?

**Comment by simon-weber** [comment]
Ran into this as well.

The "For those providers that don’t recognise the state parameter" bit of [the docs](http://python-social-auth-docs.readthedocs.io/en/latest/backends/implementation.html#oauth2) has me confused, though, since Apps [do seem to support it](https://developer.github.com/apps/building-integrations/setting-up-and-registering-github-apps/identifying-users-for-github-apps/#1-users-are-redirected-to-request-their-github-identity). What are the implications of disabling REDIRECT_STATE? Is it disabling csrf protection, or is setting STATE_PARAMETER sufficient for that?

**Comment by nkprince007** [comment]
@omab, can you please help us here? Like can we add a new backend `GitHubAppBackend` which solves the problem with `redirect_state` parameter. 

The query string construction gets messed up here.
```
https://github.com/login/oauth/authorize?client_id=<hidden_for_safety>&redirect_uri=http%3A%2F%2Flocalhost%3A8000%2Fauth%2Fcomplete%2Fgithub%2F%3Fredirect_state%3DcnL51S6cLzQWLX45zEPvpS8nbEg7i5hO&state=cnL51S6cLzQWLX45zEPvpS8nbEg7i5hO&response_type=code
```

**Comment by nkprince007** [comment]
Also, using the fix suggested by @impala2 [here](https://github.com/python-social-auth/social-core/issues/111#issue-240366048) is a bit broken too. The authorization endpoint is creating new token always, even though it is not required.

**Comment by omab** [comment]
@simon-weber, both `STATE` and `REDIRECT_STATE` purpose is to enforce a CSRF check, `REDIRECT_STATE` was added because not all the services had support for `STATE` which is specified in the spec, but a custom parameter works well with them, and is enough to ensure this check. But there are providers that don't support custom parameters in the redirect URLs, for those cases `REDIRECT_STATE` cannot be used and there are several that have this disabled.

I'm not familiar with Github Apps OAuth2 flow, if anybody can point me in the right direction I can take a look to it.

**Comment by nkprince007** [comment]
@omab, please look into https://developer.github.com/apps/building-github-apps/identifying-and-authorizing-users-for-github-apps/#identifying-users-on-your-site for further details on User-Server authentication.

**Comment by atodorov** [comment]
FTR I am using the latest version and my `SOCIAL_AUTH_GITHUB_KEY` and `SOCIAL_AUTH_GITHUB_SECRET` are pointing to the values from a GitHub App, not an OAuth app. 

The GH app itself is configured with `Request user authorization (OAuth) during installation` (I don't think that matters in my case) and points to `example.com/complete/github/`. Users are perfectly able to authorize my GitHub App and login on the site like they were with the older OAuth app. 

I don't see any particular information about how others' GitHub Apps are configured (again, not sure if and when that matters) but seems like this feature just works in the most basic use-case and we can close this issue.

I am seeing a different issue (not sure if related). Will post separately.
