### ISSUE TITLE
send_email_validation use case for partial_token

### ISSUE THREAD

**Issue by dmwyatt** [python-social-auth/social-core#130]
https://github.com/python-social-auth/social-core/blob/aedf3066cacf1c9b1546b69fd442b953fe2f921d/social_core/strategy.py#L133

That lines passes the partial_token as a fourth argument.  The [docs ](https://github.com/python-social-auth/social-docs/blob/4ad2248827455eed4adf8c95bbed6119398bc5e8/docs/pipeline.rst)say 

> This function should take three arguments strategy, backend and code

The default pipeline function `mail_validation` doesn't pass the `partial_token` kwarg, but I'm just wondering what the idea is here?

**Comment by remcinerney** [comment]
It seems the partial pipeline approach has been updated. It now makes use of an additional 'partial_token' parameter in order to resume the pipeline, so that it is no longer dependent on sessions and can be resumed between different browsers.

Look at this code from the social-examples to see how a validation function should be built with the appropriate url for re-entry into the pipeline:

`def send_validation(strategy, backend, code, partial_token):
    url = '{0}?verification_code={1}&partial_token={2}'.format(
        reverse('social:complete', args=(backend.name,)),
        code.code,
        partial_token
    )
    url = strategy.request.build_absolute_uri(url)
    send_mail('Validate your account', 'Validate your account {0}'.format(url),
              settings.EMAIL_FROM, [code.email], fail_silently=False)`

**Comment by omab** [comment]
I've updated the docs detailing this fourth parameter https://python-social-auth.readthedocs.io/en/latest/pipeline.html#email-validation
