### ISSUE TITLE
error "Incorrect padding" when using OpenID

### ISSUE THREAD

**Issue by Jibec** [python-social-auth/social-core#180]
hi there,
I'm having an issue with weblate (using django) and OpenID.

When trying to use openid features, it crashes with "Incorrect padding"
Full paste: https://paste.fedoraproject.org/paste/DgpYVI7-w8~AizEbNT5Yrw

I gave many information about this bug here:
https://github.com/WeblateOrg/weblate/issues/1799
The maintainer suggested to report the bug here.

It _may_ be related to python 3.4.

You can reproduce the error, but need to install a Debian 8, then YunoHost, then the testing branch of weblate (yunohost app install https://github.com/YunoHost-Apps/weblate_ynh/tree/testing). I can provide more information if needed.

thanks a lot for your help

**Comment by omab** [comment]
`PASTE NOT FOUND`, is this issue solved? Reopen if still relevant.

**Comment by claudep** [comment]
Please reopen this issue as I was confronted to the same error and was able to point the problem to `assoc.secret = base64.encodestring(association.secret)` in `social_django/storage.py` which is returning a bytestring. Data is then saved with the binary prefix in the database on Python 3. It should be safe to use `assoc.secret = base64.encodestring(association.secret).decode()` with both Python 2 and 3.

**Comment by claudep** [comment]
Oh, in fact it should be reported against `social-app-django` instead. @jibec, still interested in this?

**Comment by Jibec** [comment]
Well, interested? I'd love to see it fixed yes ;) I have to test again to see if the problem is still here. I delayed my upgrade because of this and keep using an old version of my app...

**Comment by dlparker** [comment]
That does not match my observations. The line of code called out in the social django bug does not get executed on the path I am talking about. I inserted ipdb.set_trace() before that line (in social_django/storage.py) and it is not reached during the sequence I am reporting. I had to make this fix is in core code, not social_django. I believe that the nature of the two bugs is similar, but they are not the same.

Put it another way. If the bug was in social django, then why would my hacky change have fixed the problem?
