### ISSUE TITLE
Facebook redirect uri

### ISSUE THREAD

**Issue by MounirMesselmeni** [python-social-auth/social-core#190]
Hello,

```
Facebook will enforce redirect uri for apps:
In 35 days, we're making a security update to Facebook Login that will invalidate calls from URIs not listed in the Valid OAuth redirect URIs field of your Facebook Login settings.

This update comes in response to malicious activity we saw on our platform, and we want to protect your app or website by requiring a new strict mode for redirect URIs. Take action now to ensure your redirect traffic continues to work.
```

If I define mywebsite.com/complete/facebook/ and enforce redirect uri it will fail because of query params ?redirect_state=something
I've seen that it's possible to pass back query params but via a state parameter https://developers.facebook.com/docs/facebook-login/manually-build-a-login-flow/#logindialog

Is this already supported and not mentioned in the documentation or should it be implemented?

Thank you

**Comment by omab** [comment]
The facebook backend already [disables the redirct state sending](https://github.com/python-social-auth/social-core/blob/c607873521eb1efe180631e842d94a134359f8b7/social_core/backends/facebook.py#L23), so that won't affect the redirect value. As for other parameters, the lib won't send anything that's not related to the auth flow, only exception is the redirect state, but it's disabled already.
