### ISSUE TITLE
`is_new` is always false

### ISSUE THREAD

**Issue by VJalili** [python-social-auth/social-core#278]
In the default auth pipeline, after `social_core.pipeline.social_auth.auth_allowed` (using Google OIDC backend), I check for `is_new` and `user` arguments. 

- `is_new=False` and `user=None` at first login (i.e., when user has not logged in the system before);
- `is_new=False` and `user=None` at re-login (i.e., when user had logged in previously, then logged out, and now is logging back in); 

I expect `is_new=True` and `user=<an_instance_of_user_object>` at re-login. Any thoughts why this does not happen?

**Comment by omab** [comment]
@VJalili, the `is_new` flag is only set to `True` when the `create_user` function is invoked, otherwise the user is not considered a new user account. Here's the code for it: https://github.com/python-social-auth/social-core/blob/fede252205368e70983079f0f45a6945fba90207/social_core/pipeline/user.py#L74
