### ISSUE TITLE
Facebook rerequest denied scopes

### ISSUE THREAD

**Issue by thiagorcdl** [python-social-auth/social-core#297]
## Problem

Currently if a Facebook user denies providing their email, but clicks on "Continue as {User Name}", the app I'm working on is linked in their Facebook account, but my application cannot proceed on creating the user account on our end.
If user tries to signup again, they are not prompted to give permissions anymore, as the app is already linked to their account on Facebook's end.

I tried going through the disconnect pipeline, but the app remains linked to their account.

## Solution

According to [Facebook documentation](https://developers.facebook.com/docs/facebook-login/manually-build-a-login-flow#reaskperms) it should be possible to ask for denied permissions without having to disconnect and re-auth an user:

> You do this by adding the auth_type=rerequest parameter to your Login Dialog URL:
```
https://www.facebook.com/v3.2/dialog/oauth?
    client_id={app-id}
    &redirect_uri={redirect-uri}
    &auth_type=rerequest
    scope=email
```

**Is there any way to currently do this in python-social-auth?**
If not, can you give me some pointers on where would be the best place to put it? I was thinking on creating a separate endpoint for re-authentication and I'd be happy to create a PR, but I'm not sure it's the best solution.

## Version

- social-auth-app-django 2.1.0
- social-auth-core 1.7.0
- Facebook 2.9

**Comment by solarissmoke** [comment]
FWIW, we were able to achieve this with:

```
SOCIAL_AUTH_FACEBOOK_AUTH_EXTRA_ARGUMENTS = {'auth_type': 'rerequest'}
```

This applies that parameter to all requests, but Facebook seems to handle this intelligently - i.e., it works even if you're requesting auth for the first time, and it will trigger a re-request for missing permissions if the app was previously authorised with a subset of the permissions you are now requesting.

**Comment by ronflima** [comment]
I have found a solution for this problem without having to deal with social-core code. For the sake of some context, I have wrote it for Django, using social-app-django. I have created a new strategy, based on DjangoStrategy with a single overridden method: get_setting. I relied on the session to save a flag that would change get_setting behavior. For my solution, I needed to ask for some extra permissions later on an account creation. By adding this flag to the session, the Facebook workflow changes the returned values to Facebook OAuth backend, as if those values were written on settings.py. 

I had to add some control in order to delete the flag from user session, so login can use settings again. Dirty, but effective.
