### ISSUE TITLE
Does Elixir AAI return ID token?

### ISSUE THREAD

**Issue by VJalili** [python-social-auth/social-core#327]
ping @tauceti2 

I am using Elixir AAI for user authentication; however, PSA fails to process its callback as the response does not contain `id_token`: 

response: 
```
{u'access_token': ... , u'token_type': u'Bearer', u'expires_in': 3599}
```

traceback:
```
...
  File "...venv/lib/python2.7/site-packages/social_core/actions.py", line 43, in do_complete
    user = backend.complete(user=user, *args, **kwargs)
  File "...venv/lib/python2.7/site-packages/social_core/backends/base.py", line 40, in complete
    return self.auth_complete(*args, **kwargs)
  File "...venv/lib/python2.7/site-packages/social_core/utils.py", line 259, in wrapper
    return func(*args, **kwargs)
  File "...venv/lib/python2.7/site-packages/social_core/backends/oauth.py", line 401, in auth_complete
    method=self.ACCESS_TOKEN_METHOD
  File "...venv/lib/python2.7/site-packages/social_core/backends/open_id_connect.py", line 196, in request_access_token
    response['id_token'],
KeyError: 'id_token'
```

**Comment by tauceti2** [comment]
Hi @VJalili,

Have you requested id_token during the client registration?

**Comment by VJalili** [comment]
I guess OIDC requirements mandate including ID token in OIDC IdPs response to successful authentication. 

I assume I can request `id_token` by checking `id_token` checkbox as shown in the following figure. If so, yes I did. However, I guess that `NYI` icon says it will not be effective.

![Screen Shot 2019-03-11 at 9 38 35 AM](https://user-images.githubusercontent.com/9027482/54140706-78820400-43e1-11e9-9607-1fb45540f2dc.png)

**Comment by kjellp** [comment]
@VJalili: it seems like you have no allowed scopes associated with your registered client yet? Did you go through the email process of registering your client to get the scopes set by the "Elixir AAI operations" after you self-registered the service? The scopes are not directly set through the web form, but has to be set by request based upon needs per individual case. This is how it looks for our registered test client:

![image](https://user-images.githubusercontent.com/4224894/54159063-5b364f80-444c-11e9-8d57-436093547458.png)

And we chose to only go for openid and email, and not the profile scope, since the additional attributes in the profile scope would (currently) not be used in Galaxy anyways, and thus it would be harder to justify requesting this scope as well when registering a client with Elixir AAI/any federated IdP.
