### ISSUE TITLE
Add backend - Apple

### ISSUE THREAD

**Issue by krimkus** [python-social-auth/social-core#370]
Add support for Sign in with Apple:

https://developer.okta.com/blog/2019/06/04/what-the-heck-is-sign-in-with-apple

**Comment by AngellusMortis** [comment]
It is important to note that this will be a requirement for mobile apps on iOS as well if they use other third party auth providers. So many apps may need to start doing this to comply with specific rules.

**Comment by kutenai** [comment]
Is anyone on the core team planning to tackle this one? 
I could possibly look at this, or someone on my team, but I've never done one before, so not sure what I'd be getting into.

**Comment by romatallinn** [comment]
Any updates?

**Comment by myers** [comment]
https://github.com/truffls/sign-in-with-apple-using-django/blob/master/backend.md maybe useful

**Comment by bmax329** [comment]
April is around the corner, wonder if we can get some more traction on this issue so many folks don't have to recreate the wheel. The PR looks solid...

**Comment by timabbott** [comment]
The python-social-auth project doesn't appear to have a healthy maintenance situation right now, which is why this issue hasn't received appropriate attention.  

Given that python-social-auth is quite well-written software and a critical piece of infrastructure for the Python community and many companies, @atodorov started a discussion on options for how to get this critical project into a state where it has a maintainer team with the capacity to do things like this: https://github.com/python-social-auth/social-core/issues/445.  

In my view it'd be especially helpful for folks at organizations that have a strong dependency of python-social-auth and can donate time or money to comment there and/or get in touch with @atodorov directly.
