### ISSUE TITLE
LinkedIn using deprecated method for access token.

### ISSUE THREAD

**Issue by DidierF** [python-social-auth/social-core#377]
Linkedin recently sent an email saying that GET requests to https://www.linkedin.com/oauth/v2/accessToken will not work as of September 15 to retrieve Access Tokens.

This should be changed to a POST request before that time.

![image](https://user-images.githubusercontent.com/5656363/60281343-c8be9c80-98d2-11e9-84e3-b817bac8d842.png)

**Comment by clovis1122** [comment]
BUMP.

**Comment by clovis1122** [comment]
@omab, do you guys accept PRs fixing this?

**Comment by jaapdeheer** [comment]
Isn't it already doing a POST for /accessToken? (See https://github.com/python-social-auth/social-core/blob/master/social_core/backends/linkedin.py#L18)

However afaiu all params are passed in the URL, not in the POST body as LinkedIn will now require.
Looks to me like `LinkedinOauth2.request_access_token`'s only purpose is to move the params from the POST body into the URL, so I suspect that simply deleting that method would make it 100% compliant.

I haven't tested this on master (I'm using a local fork since the #310 malaise), just my 2c in case it helps anyone.
