### ISSUE TITLE
"social_auth_usersocialauth.user_id" didn't match "auth_user.id"

### ISSUE THREAD

**Issue by wowkin2** [python-social-auth/social-core#47]
In my django application I have 2 tables: `auth_user` and `social_auth_usersocialauth`.
And the problem is in that the same user has different ids in these tables (`auth_user.id` and `social_auth_usersocialauth.user_id`).
So I got a problem when I wanted to figure out who is 2000th user on my site, each collection has it's own object with id = 2000.

Which of them is more reliable? The only option to register user was social auth backend.

**Comment by omab** [comment]
Th real users in your app will be stored in `auth_user`, `social_auth_usersocialauth` will just store the social-account associations (one user in `auth_user` could have many related entries in `social_auth_usersocialauth`). As per `user_id` column, it's a foreign key, so a valid reference must exists to the users table, otherwise there's an integrity error in your DB.
