### ISSUE TITLE
Question: Why is v3.4.0 not yet released to PyPI?

### ISSUE THREAD

**Issue by chdinesh1089** [python-social-auth/social-core#485]
Are there any issues with this release or is it something else? When can we expect this in PyPI?

**Comment by ozren1983** [comment]
Any updates on this questions?

**Comment by timmc-edx** [comment]
It looks like the Travis build hung on some of the environments: https://travis-ci.org/github/python-social-auth/social-core/builds/700507848

I tried running tests locally by entering a Python 3.5 virtualenv and running `pip install tox tox-travis -U pip` and then `tox`. Just like on Travis, my tests hung at `social_core/tests/backends/test_google.py::GoogleOpenIdTest::test_login`. This _also_ fails on existing version 3.3.3.

This seems to be related to a mocking issue in Google OpenID tests:

- https://github.com/python-social-auth/social-core/issues/462
- https://github.com/python-social-auth/social-core/issues/472

If those tests are fixed, maybe a 3.4.1 can be cut.

If `social_core/tests/backends/test_google.py::GoogleOpenIdTest` is deleted, all other tests pass, and it looks like there hasn't been any direct work on the Google integration since v3.3.3... so I'd say it's safe to depend on `git+https://github.com/python-social-auth/social-core.git@9d93069564a60495e0ebd697b33e16fcff14195b#egg=social-auth-core==3.4.0` for now.

**Comment by jhnbkr** [comment]
+1 we are relying on a fix for Apple ID. Is there anything I can do to help push a 3.4.x release out?

**Comment by timmc-edx** [comment]
I eventually resorted to pasting the appleid.py file (with the repo license on top) into our project, which unblocked us on Apple ID. It's possible that you could use the unreleased version but it caused other test failures for us.

**Comment by mateuszmandera** [comment]
>  it caused other test failures for us

@timmc-edx Does this mean there are regressions in 3.4.0? Which backends have been the problem for you?

**Comment by timmc-edx** [comment]
I don't know if there's a real regression.

We saw a test failure somewhere in a [fairly involved test](https://github.com/edx/edx-platform/blob/master/common/djangoapps/third_party_auth/tests/specs/test_testshib.py) that may or may not be a "legitimate" failure. It started after a commit in social-auth that fixed a pipeline bug (https://github.com/python-social-auth/social-core/commit/561642bf) so it might just be a problem with how our test was set up. The test in question appears to use the SAML backend.

It might work fine, but we were on a deadline and there wasn't a proper release to upgrade to anyhow, so we'll probably hold off on looking into that test failure until social-auth cuts a new release.

**Comment by mateuszmandera** [comment]
@timmc-edx I see, thanks for explaining that!

**Comment by andersk** [comment]
I’ve submitted #515 to remove the discontinued Google OpenID backend and get Travis passing again.

**Comment by andersk** [comment]
Go away, stale bot.

**Comment by omab** [comment]
Version 4.0.2 got released today.

**Comment by timmc-edx** [comment]
@omab Will 3.4.0 be released? It never made it to PyPI.

**Comment by omab** [comment]
@timmc-edx, for leagacy purposes, I've released 3.4.0 into pypi as well.
