### ISSUE TITLE
How can I config the openid endpoint url?

### ISSUE THREAD

**Issue by TreHack** [python-social-auth/social-core#83]
I read the source code of open_id.py, and found that the default URL is None(`URL = None`)
I want to config this URL in my project settings.py, How shoud I config?

ps: I don't think that modify the URL in the source code is a good idea.

**Comment by omab** [comment]
The easiest way is to create your own class that inherits from `OpenIdAuth` and setups such `URL` value. Take a look to [launchpad.py](https://github.com/python-social-auth/social-core/blob/master/social_core/backends/launchpad.py) backend.

Another option is to pass an `openid_identifier` parameter in your request to `/login/openid` with such value.

**Comment by TreHack** [comment]
Thanks for your reponse, @omab 
I have another question, why I can't get the other information except username, and the username seems like encrypted. How can I get the real username?
The user information I have got is below:
![image](https://cloud.githubusercontent.com/assets/17263326/26289988/e4144be0-3ed6-11e7-90ff-94c786768488.png)

**Comment by littp** [comment]
@TreHack 
I have the same problem,
username is unrecognizable
Have you solved it now?

**Comment by omab** [comment]
@TreHack, @littp, the gibberish in the username is because the pipeline will generate an unique and random one if no username name was retrieved from the provider. It pretty much depends on the service you are connecting too. A few options are:

1. Debug the `get_user_details` function to see what data is sent by the provider in use
2. Check the provider API if they use another schema to populate the username attribute

**Comment by littp** [comment]
@omab  thanks
I have already solved it
But I'm sorry   I modified your code 

link：https://segmentfault.com/a/1190000012009970
